#QQ群
QQGroup: 183995431

#--------------------------------------------------------------
# 帮助信息
HelpMessage:
  - "#资料             [查看自己的信息]"
  - "#白名单 <游戏ID>   [申请或修改白名单]"
  - "#帮助             [获取帮助]"

#--------------------------------------------------------------
# 在线玩家查询
# 正则表达式表示
OnlinePlayerKey:
  - "在线玩家"
  - "在线人数"
  - "多少.*(在线|人|玩家)"

# %players% 玩家人数
OnlinePlayerMessages:
  - "宝，现在有%players%人在服务器里哦"
  - "有%players%个小伙伴在服务器里玩！"
  - "问你妈呢，现在有%players%个人，你上线了吗"

#--------------------------------------------------------------
# 白名单
# %sender%  %old_name%   %name%
#  发送者     旧白名单    新白名单
WhiteListAddMessages:
  - "%sender%,已经为您添加白名单:%name%"
  - "%name%是你的名字对吧，%sender%，我记下来了哦"
  - "%sender%，爷知道了，%name%已经添加白名单了，快点爬去上线"

WhiteListChangeMessages:
  - "%sender%,已经为您修改白名单:%old_name%->%name%"
  - "行了行了，%sender%还要改名字，你可真是麻烦:%old_name%->%name%"

#检测到不是服务器白名单用户，提出服务器提示信息
KickMessages:
  - "你不在白名单里！请向群里的机器人申请白名单"
  - "宝，你又不在白名单里，干嘛要进服务器呢，爬去找机器人要白名单"
  - "给爷爬！！！！去群里找机器人要白名单！！"
